# Plik konfiguracyjny dla Netlify z oficjalnym pluginem dla Next.js
# To jest ostateczna i zalecana konfiguracja.

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"

# Usunięto błędną konfigurację 'publish' i 'redirects'.
# Netlify automatycznie wykryje, że to projekt Next.js i użyje poprawnych ustawień. 