# This is the only configuration needed.
# The official Netlify plugin for Next.js will automatically handle
# the build command and publish directory.

[[plugins]]
  package = "@netlify/plugin-nextjs" 